### ISSUE TITLE
ANGULAR HOMEPAGE

### ISSUE THREAD

**Issue by ikerf2001** [lmuller18/PUBGAPI#1]
I get a angular homepage and it doesnt work, can you help me what im doing wrong?
1 npm install
2 ng serve

**Comment by lmuller18** [comment]
This is an issue with my documentation. I originally scaffolded this project with the Angular CLI because I had meant to write the front-end in here as well. I need to go through and delete all of this. 

The api runs off of the `server.js` file so all that is needed to run is:
`npm install`
`npm start`

and you will need to create a `.env` file with the variable `apiKey={your_pubg_api_key}`

**Comment by ikerf2001** [comment]
Solved! Thankksss!!
